# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/anas_harby/Academic/clion-2018.3.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/anas_harby/Academic/clion-2018.3.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anas_harby/Academic/Networks/UDP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anas_harby/Academic/Networks/UDP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/anas_harby/Academic/clion-2018.3.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/anas_harby/Academic/clion-2018.3.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anas_harby/Academic/Networks/UDP/CMakeFiles /home/anas_harby/Academic/Networks/UDP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anas_harby/Academic/Networks/UDP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.s
.PHONY : client.cpp.s

file_handler.o: file_handler.cpp.o

.PHONY : file_handler.o

# target to build an object file
file_handler.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/file_handler.cpp.o
.PHONY : file_handler.cpp.o

file_handler.i: file_handler.cpp.i

.PHONY : file_handler.i

# target to preprocess a source file
file_handler.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/file_handler.cpp.i
.PHONY : file_handler.cpp.i

file_handler.s: file_handler.cpp.s

.PHONY : file_handler.s

# target to generate assembly for a file
file_handler.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/file_handler.cpp.s
.PHONY : file_handler.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/main.cpp.s
.PHONY : main.cpp.s

protocols/additive_multiplicative.o: protocols/additive_multiplicative.cpp.o

.PHONY : protocols/additive_multiplicative.o

# target to build an object file
protocols/additive_multiplicative.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/additive_multiplicative.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/additive_multiplicative.cpp.o
.PHONY : protocols/additive_multiplicative.cpp.o

protocols/additive_multiplicative.i: protocols/additive_multiplicative.cpp.i

.PHONY : protocols/additive_multiplicative.i

# target to preprocess a source file
protocols/additive_multiplicative.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/additive_multiplicative.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/additive_multiplicative.cpp.i
.PHONY : protocols/additive_multiplicative.cpp.i

protocols/additive_multiplicative.s: protocols/additive_multiplicative.cpp.s

.PHONY : protocols/additive_multiplicative.s

# target to generate assembly for a file
protocols/additive_multiplicative.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/additive_multiplicative.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/additive_multiplicative.cpp.s
.PHONY : protocols/additive_multiplicative.cpp.s

protocols/fixed_window_size_controller.o: protocols/fixed_window_size_controller.cpp.o

.PHONY : protocols/fixed_window_size_controller.o

# target to build an object file
protocols/fixed_window_size_controller.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/fixed_window_size_controller.cpp.o
.PHONY : protocols/fixed_window_size_controller.cpp.o

protocols/fixed_window_size_controller.i: protocols/fixed_window_size_controller.cpp.i

.PHONY : protocols/fixed_window_size_controller.i

# target to preprocess a source file
protocols/fixed_window_size_controller.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/fixed_window_size_controller.cpp.i
.PHONY : protocols/fixed_window_size_controller.cpp.i

protocols/fixed_window_size_controller.s: protocols/fixed_window_size_controller.cpp.s

.PHONY : protocols/fixed_window_size_controller.s

# target to generate assembly for a file
protocols/fixed_window_size_controller.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/fixed_window_size_controller.cpp.s
.PHONY : protocols/fixed_window_size_controller.cpp.s

protocols/selective_repeat.o: protocols/selective_repeat.cpp.o

.PHONY : protocols/selective_repeat.o

# target to build an object file
protocols/selective_repeat.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/selective_repeat.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/selective_repeat.cpp.o
.PHONY : protocols/selective_repeat.cpp.o

protocols/selective_repeat.i: protocols/selective_repeat.cpp.i

.PHONY : protocols/selective_repeat.i

# target to preprocess a source file
protocols/selective_repeat.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/selective_repeat.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/selective_repeat.cpp.i
.PHONY : protocols/selective_repeat.cpp.i

protocols/selective_repeat.s: protocols/selective_repeat.cpp.s

.PHONY : protocols/selective_repeat.s

# target to generate assembly for a file
protocols/selective_repeat.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/selective_repeat.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/selective_repeat.cpp.s
.PHONY : protocols/selective_repeat.cpp.s

protocols/slow_starter.o: protocols/slow_starter.cpp.o

.PHONY : protocols/slow_starter.o

# target to build an object file
protocols/slow_starter.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/slow_starter.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/slow_starter.cpp.o
.PHONY : protocols/slow_starter.cpp.o

protocols/slow_starter.i: protocols/slow_starter.cpp.i

.PHONY : protocols/slow_starter.i

# target to preprocess a source file
protocols/slow_starter.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/slow_starter.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/slow_starter.cpp.i
.PHONY : protocols/slow_starter.cpp.i

protocols/slow_starter.s: protocols/slow_starter.cpp.s

.PHONY : protocols/slow_starter.s

# target to generate assembly for a file
protocols/slow_starter.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/slow_starter.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocols/slow_starter.cpp.s
.PHONY : protocols/slow_starter.cpp.s

protocols/stop_and_wait.o: protocols/stop_and_wait.cpp.o

.PHONY : protocols/stop_and_wait.o

# target to build an object file
protocols/stop_and_wait.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/stop_and_wait.cpp.o
.PHONY : protocols/stop_and_wait.cpp.o

protocols/stop_and_wait.i: protocols/stop_and_wait.cpp.i

.PHONY : protocols/stop_and_wait.i

# target to preprocess a source file
protocols/stop_and_wait.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/stop_and_wait.cpp.i
.PHONY : protocols/stop_and_wait.cpp.i

protocols/stop_and_wait.s: protocols/stop_and_wait.cpp.s

.PHONY : protocols/stop_and_wait.s

# target to generate assembly for a file
protocols/stop_and_wait.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/protocols/stop_and_wait.cpp.s
.PHONY : protocols/stop_and_wait.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.s
.PHONY : server.cpp.s

tcp_socket.o: tcp_socket.cpp.o

.PHONY : tcp_socket.o

# target to build an object file
tcp_socket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tcp_socket.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tcp_socket.cpp.o
.PHONY : tcp_socket.cpp.o

tcp_socket.i: tcp_socket.cpp.i

.PHONY : tcp_socket.i

# target to preprocess a source file
tcp_socket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tcp_socket.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tcp_socket.cpp.i
.PHONY : tcp_socket.cpp.i

tcp_socket.s: tcp_socket.cpp.s

.PHONY : tcp_socket.s

# target to generate assembly for a file
tcp_socket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tcp_socket.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tcp_socket.cpp.s
.PHONY : tcp_socket.cpp.s

types.o: types.cpp.o

.PHONY : types.o

# target to build an object file
types.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/types.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/types.cpp.o
.PHONY : types.cpp.o

types.i: types.cpp.i

.PHONY : types.i

# target to preprocess a source file
types.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/types.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/types.cpp.i
.PHONY : types.cpp.i

types.s: types.cpp.s

.PHONY : types.s

# target to generate assembly for a file
types.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/types.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/types.cpp.s
.PHONY : types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... client"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... file_handler.o"
	@echo "... file_handler.i"
	@echo "... file_handler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... protocols/additive_multiplicative.o"
	@echo "... protocols/additive_multiplicative.i"
	@echo "... protocols/additive_multiplicative.s"
	@echo "... protocols/fixed_window_size_controller.o"
	@echo "... protocols/fixed_window_size_controller.i"
	@echo "... protocols/fixed_window_size_controller.s"
	@echo "... protocols/selective_repeat.o"
	@echo "... protocols/selective_repeat.i"
	@echo "... protocols/selective_repeat.s"
	@echo "... protocols/slow_starter.o"
	@echo "... protocols/slow_starter.i"
	@echo "... protocols/slow_starter.s"
	@echo "... protocols/stop_and_wait.o"
	@echo "... protocols/stop_and_wait.i"
	@echo "... protocols/stop_and_wait.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... tcp_socket.o"
	@echo "... tcp_socket.i"
	@echo "... tcp_socket.s"
	@echo "... types.o"
	@echo "... types.i"
	@echo "... types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

